//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeClinicManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpd
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Slipno { get; set; }
        public string Name { get; set; }
        public string Relation { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Cnic { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Doctoropd { get; set; }
        public string Reffered { get; set; }
        public string Remarks { get; set; }
        public string Services { get; set; }
        public string Eye { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Image { get; set; }
    }
}
